INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (1, 'Pororo', now(), now());

INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (2, 'Lupi', now(), now());

INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (3, 'Eddie', now(), now());
